### PR TITLE
[RU] meta page for staffs

### PR DESCRIPTION
**Pull request by Dm-Boo**
Translation for meta in staff folder

That's a test if I can merge by myself now xd

### CODE REVIEW

**Comment by Dm-Boo** [comment]
Do I need smth to type to "review" my pull request?..

Nope, I'm wrong. Just no perms xD

**Comment by Yunaferrar** [comment]
No you cant review your pull request xD It is smth dot or I do. I thinkkkk. Anyway let me check

**Comment by Yunaferrar** [comment]
Thanks for contributing btw!! :D

**Comment by Dm-Boo** [comment]
wrong folder for meta, I'm blind + I can't review my own request so I'll close this one and upload all my saved translations in another single pull request :p

**Pull request closed without merging**
